-- -*- coding: UTF-8; mode: sql; sql-product: ansi; -*-

DROP SCHEMA PUBLIC CASCADE;

-- テーブル
CREATE TABLE "t_sample" (
    "key" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
    "value" VARCHAR(100) NOT NULL,
    PRIMARY KEY("key")
);
INSERT INTO "t_sample"("value") VALUES('hogehoge');

-- ビュー
CREATE VIEW "v_sample" AS SELECT * FROM "t_sample";
